name: MIUI

on: # [push]
  workflow_dispatch:
  watch:
    types: [started]

env:
  TG_CHAT_ID:  ${{ secrets.TG_CHAT_ID }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029
    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Initialize environment
          run: |
           chmod +x initialize
           bash initialize
        - name: Starting build
          run: |
           git clone --depth=1 https://github.com/Novik-XIV/LINUX-KERNEL-SM6150 -b SONIC SONIC
           cp build.sh SONIC && cd SONIC
           chmod +x build.sh && bash build.sh
